
/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To analyze data distribution and magnitude across different dimensions
    - To understand segmentation patterns in customers, products, and sales
    - To identify top performers and concentration patterns by category
    - To calculate aggregated metrics using dimensional groupings

SQL Functions Used:
    - COUNT / SUM / AVG
    - GROUP BY
    - ORDER BY
    - LEFT JOIN

Tables Used:
    - gold.dim_customers
    - gold.dim_products
    - gold.fact_sales
===============================================================================
*/
USE DataWarehouse

-- Total Customers By Countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Total Customers By Gender

SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Total Products By Category

SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- Average Cost In Each Category

SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- total revenue generated for each category

SELECT
p.category,
SUM(f.sales_amount) total_revenue
FROM
gold.fact_sales f
LEFT JOIN
gold.dim_products p
ON p.product_key=f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Total Revenue Generated by Each Customer


SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) total_revenue
FROM
gold.fact_sales f
LEFT JOIN
gold.dim_customers c
ON c.customer_key=f.customer_key
GROUP BY 
   c.customer_key,
   c.first_name,
   c.last_name
ORDER BY total_revenue DESC


-- Distribution of Sold Items Across Countries

SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
